version: "3.9"
services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
  mariadb:
    image: mariadb:11
    container_name: sistemabiblioteca_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: biblioteca
      MARIADB_USER: paco
      MARIADB_PASSWORD: pacopass
    ports:
      - "3306:3306"

  sistemabiblioteca:
    build: .
    container_name: sistemabiblioteca
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
      - sonarqube
    restart: always

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
